### PR TITLE
feature: CLI dispatcher

### LINKED ISSUE #62: pipx support for migrate script
### Problem
I have to install this project just to run it once

### Proposed Solution

We could add a `[project.scripts]` table, either with a single entrypoint like

```toml
[project.scripts]
hatch-jupyter-builder = 'hatch_jupyter_builder.cli:run'
```

which can be called as `hatch-jupyter-builder migrate .` and `hatch-jupyter-builder compare-migrated a b [wheel|sdist]`.

Or we could add multiple scripts:

```toml
[project.scripts]
hjb-migrate = 'hatch_jupyter_builder.migrate:run'
hjb-compare-migrated = 'hatch_jupyter_builder.compare_migrated:run'
```

### PR DESCRIPTION
**Pull request by flying-sheep**
I made all CLI packages follow a convention:

- `def make_parser(parser=None, prog=None)` either creates a parser or adds arguments to one that’s being passed
- `def run(args=None)` either runs from passed `args` (`argparse.Namespace`) or parses `sys.argv` using `make_parser`

Together, that allows to maintain backwards compatibility, as `python -m hatch_jupyter_builder.migrate` is still possible and works the same as the new `hatch-jupyter-builder migrate`.

Fixes #62

Results:

```console
$ hatch-jupyter-builder -h
usage: hatch-jupyter-builder [-h] {migrate,compare-migrated} ...
...
$ python -m hatch_jupyter_builder -h
usage: /usr/bin/python -m hatch_jupyter_builder [-h] {migrate,compare-migrated} ...

positional arguments:
  {migrate,compare-migrated}

options:
  -h, --help            show this help message and exit
```

```console
$ hatch-jupyter-builder migrate -h
usage: hatch-jupyter-builder migrate [-h] target_dir
...
$ python -m hatch_jupyter_builder migrate -h
usage: /usr/bin/python -m hatch_jupyter_builder migrate [-h] target_dir
...
$ python -m hatch_jupyter_builder.migrate -h
usage: /usr/bin/python -m hatch_jupyter_builder.migrate [-h] target_dir

positional arguments:
  target_dir  Target Directory

options:
  -h, --help  show this help message and exit
```

```console
$ hatch-jupyter-builder compare_migrated -h
usage: hatch-jupyter-builder compare_migrated [-h] source_dir target_dir dist_name
...
$ python -m hatch_jupyter_builder compare_migrated -h
usage: /usr/bin/python -m hatch_jupyter_builder compare_migrated [-h] source_dir target_dir dist_name
...
$ python -m hatch_jupyter_builder.compare_migrated -h
usage: /usr/bin/python -m hatch_jupyter_builder.compare_migrated [-h] source_dir target_dir dist_name

positional arguments:
  source_dir  Source Directory
  target_dir  Target Directory
  dist_name   Dist name

options:
  -h, --help  show this help message and exit
```

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Very nice, thank you!

**Comment by blink1073** [comment]
Failure is unrelated.  Thanks again!

**Comment by blink1073** [comment]
https://github.com/jupyterlab/hatch-jupyter-builder/releases/tag/v0.6.0

**Comment by flying-sheep** [comment]
neat, thank you for the quick review!

**Pull request merged**
